version: "3.9"

services:
  db:
    image: postgres:16
    container_name: workmate_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 4g1tw0rkm4t3
      POSTGRES_DB: workmate
    ports:
      - "5555:5555"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: workmate_api
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    environment:
      PORT: "8080"
      JWT_SECRET: 4g1tw0rkm4t3"
      DATABASE_URL: "postgres://postgres:postgres@db:5432/postgres?sslmode=disable"
    ports:
      - "8080:8080"

volumes:
  db_data:


